variables:
  NODE_VERSION: '14.17.0'
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

trigger:
  branches:
    include:
      - development

pr:
  branches:
    include:
      - develop
  paths:
    exclude:
      - README/*

pool:
  vmImage: 'ubuntu-latest'

stages:
  # A) Build and code validation (always run)
  - stage: Build
    dependsOn: []
    jobs:
      # A1) Checkout, install module and build code (use Windows OS)
      - job: make_build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - template: azure-templates/make-build-steps.yml
            parameters:
              make: build
          - script: |
              yarn
            displayName: 'Build'
            
      # A2) Analyze source code to find errors with lint
      - job: lint
        steps:
          - template: azure-templates/make-build-steps.yml
            parameters:
              make: install_dependencies

          - script: |
              yarn lint
            displayName: 'Lint'
  # B) Run unit tests (use Linux OS, also required to generate certificates)
  - stage: Test
    dependsOn: []
    jobs:
      - job: unit_tests
        steps:
          - template: azure-templates/make-build-steps.yml
            parameters:
              make: build

          - script: |
              yarn test:cov
            displayName: 'Unit tests exec'
          - bash: |
              bash <(curl -s https://codecov.io/bash)
            displayName: 'Code coverage'